# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Isaac's Blog
subtitle: 学习、研究 IT 知识，分享技术经验和见解
description: IT 技术博客 / 前端开发 / 性能优化 / 架构设计 / Linux / 最佳实践
keywords:
  - Blog
  - Linux
  - NodeJS
  - JavaScript
  - 性能优化
  - 架构设计
  - IT 技术
  - 计算机科学
  - Web 开发
  - 前端工程化
author: Isaac Kam
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://isaaxite.pages.dev/
# url: https://isaaxite.github.io/
# url: http://localhost:4000/
root: /
# permalink: :year/:month/:day/:title/
# permalink: resources/:year/:month/:day/:title/
# permalink: resources/:title/
# slugpath is var defined in post's front-matter, and it is defined by myself, so it is not a default var in hexo, but it is more intuitive than :title, and I can use it to set the permalink of post flexibly.
permalink: blog/:slugpath/
permalink_defaults: blog/:name/
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
  exclude_languages:
    - mermaid
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
  exclude_languages:
    - mermaid

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
exindex_generator_enable: true
exindex_generator:
  path: ''
  per_page: 10
  order_by: -date
  pin_top:
    tags: topping

  pin_bottom:
    # exclude article which tag is Hexo, exp tags: <tag1>[,<tag2>,...]
    tags:
     - bottoming
     - writting

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
# Docs: https://hexo.io/docs/one-command-deployment
# deploy:
#   type: git
#   repository: https://github.com/isaaxite/blog
#   branch: master

deploy:
  # - type: git
  #   repo: git@github.com:isaaxite/blog.git
  #   branch: master
  - type: git
    repo: git@github.com:isaaxite/isaaxite.github.io.git
    branch: gh-pages
# deploy:
#   type: git
#   repo:
#     github:
#       url: https://github.com/isaaxite/blog.git
#       branch: master
#       token: $GITHUB_TOKEN
    # name: isaaxite
    # email: isaacgun@outlook.com

feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

language: zh-CN

neat_enable: true

search:
  path: search.xml
  field: all
  content: true
  format: html

hide_posts:
  # Should hexo-hide-posts be enabled.
  enable: true

  # The front-matter key for flagging hidden posts.
  # You can change the filter name if you like.
  filter: hidden

  # Add "noindex" meta tag to prevent hidden posts from being indexed by search engines.
  noindex: true

  # Generators in the allowlist will have access to the hidden posts.
  # Common generators in Hexo: 'index', 'tag', 'category', 'archive', 'sitemap', 'feed'
  allowlist_generators: ['archive']

  # Generators in the blocklist can *not* access the hidden posts.
  # The allowlist has higher priority than the blocklist, if both set.
  # blocklist_generators: ['*']

sitemap:
  path:
    - sitemap.cloudflare.xml
    - sitemap.cloudflare.txt
  # template: ./sitemap_template.xml
  # template_txt: ./sitemap_template.txt

  # `plagiarize` is the config for scripts/sitemap-plagiarize.js
  plagiarize:
    - url: https://isaaxite.github.io
      path:
        - sitemap.xml
        - sitemap.txt
        - blog/sitemap.xml
        - blog/sitemap.txt

    - url: https://isaaxite.indevs.in
      path:
        - sitemap.indevsin.xml
        - sitemap.indevsin.txt
  rel: false
  tags: false
  categories: false

alias:
  blog/index.html: /

# Favicon - power by `scripts/favicon.js`
# `rel` is optional, and it will be set to 'icon' by default if not specified
favicon:
  - href: /favicon.ico
    sizes: 32x32

  - href: /icon.svg
    type: image/svg+xml

  - rel: apple-touch-icon
    href: /apple-touch-icon.png
